on: pull_request

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      # Fixes prettier complaining about crlf line endings
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - run: yarn install
      - run: xvfb-run -a yarn test
        env:
          VSCODE_DB_SECRET: ${{ secrets.VSCODE_DB_SECRET }}
        if: runner.os == 'Linux'
      - run: yarn test
        env:
          VSCODE_DB_SECRET: ${{ secrets.VSCODE_DB_SECRET }}
        if: runner.os != 'Linux'
